"""add user_congratulations

Revision ID: 7cc8b857eedd
Revises: 7a87c283b65a
Create Date: 2024-06-13 18:50:29.227720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc8b857eedd'
down_revision = '7a87c283b65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercongratulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('congratulated_id', sa.Integer(), nullable=True),
    sa.Column('text_greeting', sa.Text(), nullable=False),
    sa.Column('data_greeting', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['congratulated_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercongratulations')
    # ### end Alembic commands ###
